cc = gcc

CFLAGS = 

tiny: main.o util.o scan.o parse.o symtab.o analyze.o code.o cgen.o
	gcc -o tiny -gdwarf-2 -g3 main.o util.o scan.o parse.o symtab.o analyze.o code.o cgen.o

main.o: main.c globals.h util.h scan.h parse.h analyze.h cgen.h
	gcc -gdwarf-2 -g3 -c main.c

util.o: util.c util.h globals.h
	gcc -gdwarf-2 -g3 -c util.c

scan.o: scan.c scan.h util.h globals.h
	gcc -gdwarf-2 -g3 -c scan.c

parse.o: parse.c parse.h scan.h globals.h util.h
	gcc -gdwarf-2 -g3 -fno-builtin -c parse.c

symtab.o: symtab.c symtab.h
	gcc -gdwarf-2 -g3 -c symtab.c

analyze.o: analyze.c globals.h symtab.h analyze.h
	gcc -gdwarf-2 -g3 -c analyze.c

code.o: code.c code.h globals.h
	gcc -gdwarf-2 -g3  -c code.c

cgen.o: cgen.c globals.h symtab.h code.h cgen.h
	gcc -gdwarf-2 -g3 -c cgen.c


clean: 
	rm -f tiny main.o util.o scan.o parse.o symtab.o analyze.o code.o cgen.o lex/lex.yy.c yacc/tiny.tab.c  

tm: tm.c
	gcc -gdwarf-2 -g3 tm.c
